### PR TITLE
fix: Wrap preconditions in a closure to prevent early return

### LINKED ISSUE #66: bug: naked expressions need to be guarded for `return`s
Same thing that was fixed for `fn` bodies in #57.

### PR DESCRIPTION
**Pull request by brandonpollack23**
In the same vein as #57 , preconditions also must be wrapped in a closure to correctly handle any included return statements and prevent them from returning from the instrumented function.

This PR also modifies the tests for execution order to include the return keyword, removes the hacky Parse implementations used in those tests, and instead constructs the appropriate *Condition structs directly.

Fixes #66

### CODE REVIEW

**Comment by brandonpollack23** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.com/github/pr/mkovaxx/anodized/69?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#69** <a href="https://app.graphite.com/github/pr/mkovaxx/anodized/69?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/mkovaxx/anodized/69?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#68** <a href="https://app.graphite.com/github/pr/mkovaxx/anodized/68?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/anodized-core/src/annotate/tests.rs [hunk 1]
```diff
@@ -14,6 +14,43 @@ fn simple_spec() {
...
+    let expected = Spec {
+        requires: vec![parse_quote! { is_valid(x) }],
+        maintains: vec![],
+        captures: vec![],
+        ensures: vec![parse_quote! { output > x }],
+    };
+
+    assert_spec_eq(&spec, &expected);
+}
+
```
Comment (mkovaxx) [inline crates/anodized-core/src/annotate/tests.rs]: <p class='graphite__hidden'><i>[Re: lines +6 to +39]</i></p>
Please re-work these so they don't depend on the custom Parser implementations. In general, a PostCondition cannot be parsed in isolation, because the default `output` binding may be overridden by a `binds:` clause in the `spec`. To keep the rest of the test logic easy to understand, it's better not to rely on custom parsers, even if that makes the tests slightly more verbose. (Most of these tests will be edited usin AI anyway, so verbosity is not an issue.)
<p class='graphite__hidden'>See this comment inline on <a href="https://app.graphite.com/github/pr/mkovaxx/anodized/69?utm_source=unchanged-line-comment">Graphite</a>.</p>

**Review by mkovaxx — CHANGES_REQUESTED** [review]
This is looking good, thanks!

Please add/extend an integration test in `anodized` to demonstrate that `return` statements in conditions are now handled correctly.

The easiest way is likely to change the following test case to be "maximally evil":
https://github.com/mkovaxx/anodized/blob/478df504e2044e710e234162c2a14cbeb48319bf/crates/anodized/tests/execution_order.rs#L3-L24

**Comment by brandonpollack23** [comment]
This change should do it

File: crates/anodized-core/src/annotate/tests.rs (hunk 1 above)
Comment (brandonpollack23) [reply crates/anodized-core/src/annotate/tests.rs]: Ah yeah I was just following the already established pattern.  Ill completely remove the custom parsers here that were there as well.  I thnk that's better too.  I saw in the other comment you wanted to keep this PR small and do that later, but I think it makes sense to clean it up now so I went ahead

File: crates/anodized-core/src/test_util.rs [hunk 2]
```diff
@@ -76,15 +66,15 @@ where
     }
 }
 
-fn assert_condition_eq(left: &Condition, right: &Condition, msg_prefix: &str) {
+fn assert_condition_eq(left: &PreCondition, right: &PreCondition, msg_prefix: &str) {
```
Comment (mkovaxx) [inline crates/anodized-core/src/test_util.rs]:
```suggestion
fn assert_precondition_eq(left: &PreCondition, right: &PreCondition, msg_prefix: &str) {
```

File: crates/anodized-core/src/annotate/tests.rs [hunk 3]
```diff
@@ -3,6 +3,52 @@ use crate::test_util::assert_spec_eq;
 use super::*;
 use syn::parse_quote;
 
+#[test]
+fn simple_spec_parse_quote() {
```
Comment (mkovaxx) [inline crates/anodized-core/src/annotate/tests.rs]: Including "parse quote" in the name here is meaningless. Please rename to better reflect what is being tested here.

File: crates/anodized-core/src/annotate/tests.rs [hunk 4]
```diff
@@ -3,6 +3,52 @@ use crate::test_util::assert_spec_eq;
...
+            closure: parse_quote! { |output| output > x },
+            cfg: None,
+        }],
+    };
+
+    assert_spec_eq(&spec, &expected);
+}
+
+#[test]
+fn simple_spec_parse_quote_implicit_output() {
```
Comment (mkovaxx) [inline crates/anodized-core/src/annotate/tests.rs]: Including "parse quote" in the name here is meaningless. Please rename to better reflect what is being tested here.

File: crates/anodized-core/src/lib.rs [hunk 5]
```diff
@@ -12,20 +12,21 @@ mod test_util;
...
 
-/// A condition represented by a `bool`-valued expression.
+/// A precondition represented by a `bool`-valued expression.
 #[derive(Debug)]
-pub struct Condition {
-    /// The `bool`-valued expression.
-    pub expr: Expr,
+pub struct PreCondition {
+    /// The closure that validates the precondition,
+    /// takes no, e.g. `|| input.is_valid()`.
```
Comment (mkovaxx) [inline crates/anodized-core/src/lib.rs]:
```suggestion
    /// takes no input, e.g. `|| input.is_valid()`.
```

File: crates/anodized/tests/execution_order.rs [hunk 6]
```diff
@@ -1,9 +1,18 @@
 use anodized::spec;
 
+/// This function should never return false, but the should work
```
Comment (mkovaxx) [inline crates/anodized/tests/execution_order.rs]: Remove

File: crates/anodized/tests/execution_order.rs [hunk 7]
```diff
@@ -1,9 +1,18 @@
...
+            if log.len() == 1 {
+                return log.push("requires2") == ();
+            }
+            else {
+                return false
+            }
+        }
     ],
     maintains: [
         log.push("maintains1") == (),
```
Comment (mkovaxx) [inline crates/anodized/tests/execution_order.rs]: <p class='graphite__hidden'><i>[Re: lines +18 to +19]</i></p>
```gt_suggestion
        return log.push("maintains1") == (),
        return log.push("maintains2") == (),
```
<p class='graphite__hidden'>See this comment inline on <a href="https://app.graphite.com/github/pr/mkovaxx/anodized/69?utm_source=unchanged-line-comment">Graphite</a>.</p>

Comment (mkovaxx) [inline crates/anodized/tests/execution_order.rs]: <p class='graphite__hidden'><i>[Re: lines +26 to +27]</i></p>
```gt_suggestion
        return log.push("ensures1") == (),
        return log.push("ensures2") == (),
```
<p class='graphite__hidden'>See this comment inline on <a href="https://app.graphite.com/github/pr/mkovaxx/anodized/69?utm_source=unchanged-line-comment">Graphite</a>.</p>

**Review by mkovaxx — CHANGES_REQUESTED** [review]

**Comment by brandonpollack23** [comment]
### Merge activity

* **Jan 21, 5:05 AM UTC**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.com/github/pr/mkovaxx/anodized/69).
